# Generated by Django 4.0.6 on 2022-07-10 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Kategor', models.CharField(max_length=20, verbose_name='Kategor')),
            ],
        ),
    ]
