# Generated by Django 4.0.6 on 2022-07-10 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forwork', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='Kategor',
            field=models.CharField(max_length=20, verbose_name='Kategory'),
        ),
    ]
