# Generated by Django 4.0.6 on 2022-07-10 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forwork', '0002_alter_role_kategor'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='Name',
            field=models.CharField(default='Some String', max_length=40, verbose_name='Name'),
        ),
    ]
