# Generated by Django 4.0.6 on 2022-07-10 07:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forwork', '0003_role_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Staf',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FIO', models.CharField(max_length=60, verbose_name='FIO')),
                ('Gender', models.CharField(max_length=1, verbose_name='Gender')),
                ('Age', models.IntegerField(verbose_name='Age')),
                ('Post', models.ForeignKey(default='1', on_delete=django.db.models.deletion.SET_DEFAULT, to='forwork.role')),
            ],
        ),
    ]
